todos/urls.py
from django.urls import path
from todos import views
from decouple import config

app_name = 'todos'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('update/<int:pk>/', views.update, name="update"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

wunderlist/urls.py
from django.contrib import admin
from django.urls import path, include
from decouple import config
from todos import views

token = config('TOKEN')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path(f'{token}/', views.telegram),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json
from pprint import pprint as pp
from .models import Todo
import requests
from decouple import config

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'todos/index.html', context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        Todo.objects.create(title=title, due_date=due_date)
        return redirect('todos:index')
    else:
        return render(request, 'todos/create.html')

def update(request, pk):
    todo = get_object_or_404(Todo, id=pk)

    if request.method == 'POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        todo.title = title
        todo.due_date = due_date
        todo.save()
        return redirect('todos:index')
    else: 
        context = {
            'todo': todo
        }
        return render(request, 'todos/update.html', context)

def delete(request, pk):
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()

    return redirect('todos:index')

@csrf_exempt
def telegram(request):
    print(request.method)
    res = json.loads(request.body)

    text = res.get('message').get('text')
    chat_id = res.get('message').get('chat').get('id')
    base = 'https://api.telegram.org'
    token = config('TOKEN')
    url = f'{base}/bot{token}/sendMessage?text={text}&chat_id={chat_id}'
    requests.get(url)
    return HttpResponse('아무메세지')

todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>WunderList</title>
</head>
<body>
  <a href="{% url 'todos:create' %}">글작성하기</a>
  <a href="{% url 'todos:index' %}">글모아보기</a>
  {% block body %}
  {% endblock %}
</body>
</html>

todos/templates/todos/create.html
{% extends 'todos/base.html' %}
{% block body %}
<h1>여기는 새글 작성입니다.</h1>
<form action="{% url 'todos:create' %}" method="post">
  {% csrf_token %}
  <input type="text" name="title">
  <input type="date" name="due-date">
  <input type="submit">
</form>
{% endblock %}

todos/templates/todos/edit.html
{% extends 'todos/base.html' %}
{% block body %}
<h1>여기는 새글 작성입니다.</h1>
<form action="{% url 'todos:update' todo.id %}" method="post">
  {% csrf_token %}
  <input type="text" name="title" value="{{todo.title}}">
  <input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
  <input type="submit">
</form>
{% endblock %}

todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
  <h1>여기는 인덱스입니다.</h1>
  {% for todo in todos %}
    <li>{{ todo.due_date }} : {{ todo.title }}</li>
    <a href="{% url 'todos:update' todo.id %}">수정</a>
    <a href="{% url 'todos:delete' todo.id %}">삭제</a>
  {% endfor %}
{% endblock %}

todos/templates/todos/new.html
{% extends 'todos/base.html' %}
{% block body %}
<h1>여기는 새글 작성입니다.</h1>
<form action="{% url 'todos:create' %}" method="post">
  {% csrf_token %}
  <input type="text" name="title">
  <input type="date" name="due-date">
  <input type="submit">
</form>
{% endblock %}

todos/templates/todos/update.html
{% extends 'todos/base.html' %}
{% block body %}
<h1>여기는 새글 작성입니다.</h1>
<form action="{% url 'todos:update' todo.id %}" method="post">
  {% csrf_token %}
  <input type="text" name="title" value="{{todo.title}}">
  <input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
  <input type="submit">
</form>
{% endblock %}